### PR TITLE
Safer way to redefine render method

### LINKED ISSUE #26: Doesn't work when used together with babel-plugin-transform-decorators-legacy
Yep, I know that both transforms are use-on-your-own-risk kind of thing) But just FYI, these transforms don't work together. You get this error in console:

```
Uncaught TypeError: Cannot set property render of #<ComponentName> which has only a getter
```

removing either babel-plugin-transform-decorators-legacy or react-transform-catch-errors fixes the issue.

### PR DESCRIPTION
**Pull request by smashercosmo**
fixes https://github.com/gaearon/react-transform-catch-errors/issues/26

### CODE REVIEW

**Comment by smashercosmo** [comment]
Is there anything that stops this from merging?

**Comment by smashercosmo** [comment]
@gaearon ???

**Comment by gaearon** [comment]
Sorry, I have a new job and haven’t been keeping up with the stuff

**Comment by smashercosmo** [comment]
No worries) Glad you found time for me) Thx

**Comment by gaearon** [comment]
Can you please submit an additional PR that makes sure we preserve  `enumerable` of the original method?

**Comment by smashercosmo** [comment]
Hope, new release will come shortly)

**Comment by smashercosmo** [comment]
> Can you please submit an additional PR that makes sure we preserve enumerable of the original method?

Ok.

**Comment by gaearon** [comment]
Something like:

``` js
var originalRenderDescriptor = Object.getOwnPropertyDescriptor(ReactClass.prototype, 'render');
Object.defineProperty(ReactClass.prototype, 'render', {
  enumerable: originalRenderDescriptor && originalRenderDescriptor.enumerable || true,
  ...
})
```

**Comment by smashercosmo** [comment]
Yes, I got it

**Pull request merged**
